[tool.poetry]
name = "metadata-driven-frame-work-pipeline"
package-mode = false   # <--- Add this exact line here
version = "0.1.0"
description = "A metadata-driven pipeline orchestrator with SQLite backing"
authors = ["Olanrewaju Micheal Akinbode <mykeylife6@gmail.com>"]

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "W", "I", "N", "UP", "B", "C4"]
ignore = []

# --- Add this section to resolve the ModuleNotFoundError ---
[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests", "pipeline/tests"]
