sonar.projectKey=metadata-driven-frame-work-pipeline
sonar.projectName=metadata-driven-frame-work-pipeline
sonar.projectVersion=1.0.0
sonar.sources=pipeline,seed_metadata.py,orchestrator.py
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
